### ISSUE TITLE
TypeError: document.getElementsByTagName(...)[0].insertAdjacentElement is not a function

### ISSUE THREAD

**Issue by agonzalezmurua** [GoogleChromeLabs/prerender-loader#21]
I was trying to implement this loader by following the instruction provided in the readme but when trying to bundle in production I'm getting this error:

```
 ERROR in ./src/index.html (./node_modules/prerender-loader/dist/prerender-loader.js?string!./src/index.html)
    Module build failed: TypeError: document.getElementsByTagName(...)[0].insertAdjacentElement is not a function
        at u (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:57:7005)
        at Object.k7yg (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:57:124662)
        at r (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:1:138)
        at Object.0 (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:1:4410)
        at r (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:1:138)
        at PRERENDER_RESULT.+JVh (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:1:839)
        at eval (eval at <anonymous> (/Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37), <anonymous>:1:848)
        at eval (<anonymous>)
        at /Users/_myuser_/Developer/temp/node_modules/prerender-loader/dist/prerender-loader.js:206:37
        at <anonymous>
```

**Comment by developit** [comment]
Something you're using is inserting an element as a side-effect.
My guess is that it's something you're using for styling, like `style-loader` or `styled-components`.
Can you provide details on what you're trying to render or what tech you're using?

**Comment by agonzalezmurua** [comment]
I'm utilizing `react` with a custom component library which uses `styled-components`
It seems that styled components is the root of the problem because as soon as I removed the library the project started compiling, does it mean that I cannot use `styled-components`?
