### ISSUE TITLE
ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by JaceHensley** [GoogleChromeLabs/prerender-loader#32]
I'm trying to set this up for a react+TS project. I have my main entry point set up like this:

```tsx
import * as React from 'react'
import {render} from 'react-dom'

class App extends React.Component {
  componentDidMount() {
    document.dispatchEvent(new Event('prerender-ready'))
  }

  render() {
    ...
  }
}

render(<App/>, document.querySelector('#root'))

export default () => {
  await Promise((resolve) => {
    document.addEventListener('prerender-ready', () => resolve())
    render(<App/>, document.querySelector('#root'))
  })
}

```

And when trying to prerender I get the following error:

```
Error: Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.dispatchError (/.../node_modules/prerender-loader/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
    at Request.client.on.err (/.../node_modules/prerender-loader/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/.../node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) undefined
```

And my webpack.config.js looks like this:

```js
...
plugins: [
  ...['/', ...].map(url => {
    return new HtmlWebpackPlugin({
      filename: `${url}/main.html`,
      template:
        '!!prerender-loader?' +
        encodeURIComponent(
          JSON.stringify({
            string: true,
            documentUrl: `http://localhost:3000${url}`,
          })
        ) +
        `!${paths.clientHtml}`,
    })
  }
  ...
]
...
```

I feel like it's really close to working for me, but I'm not sure where to look from here. My prod webpack config doesn't use webpack-dev-server/webpack-serve, not sure if that's needed. Any help would be greatly appreciated, thanks!

**Comment by JaceHensley** [comment]
Closing this, the cause was I am using localForage in the app but wasn't escaping from it during pre-rendering so JSDOM was, I assume, panicking and exiting.
